### PR TITLE
Fix prototypes chargen

### PR DESCRIPTION
**Pull request by ChrisLR**
This should address #112 .. at least partially.
It introduces new dataclasses that wrap around evennia prototypes to provide something easier to use
and fixes the chargen options to use them.
It fixes a few crashes and the item displays

### CODE REVIEW

**Comment by Griatch** [comment]
Opinion: Considering the intent of Ainneve is for people to read the code to learn Evennia, not sure introducing dataclasses makes for a good example of prototype usage ... it rather adds another layer of complexity to wade through when learning ...?

**Comment by ChrisLR** [comment]
Its true, dataclasses might be harder to understand for beginners but I introduced them to make prototypes easier to work with in other parts of the code, particularly the attributes. The prototype attributes are given as a list of tuples which is a bit of a hassle because the code constantly accesses attributes by name. 
Would it be better if I  instead insert a new dict inside the prototype to access the attributes by name?
I could also just use  the new dict in the code that requires it, instead of using the prototype dict

**Comment by friarzen** [comment]
Yes, the new dict with attributes by name seems like a much more
straight-forward approach.
The only other thing I thought about was to add a bit of guard code around
missing keys or functions that could return NoneType or similar.
Thanks for the updates, I really appreciate the switch to fstrings, and am
looking forward to merging this.

--Friarzen

**Comment by ChrisLR** [comment]
Alright, I've applied the changes discussed, noticed mobs are spawned as "A normal person" but I will investigate that in another PR

**Review by friarzen — APPROVED** [review]

**Comment by friarzen** [comment]
Ok, I've tested it and it looks good!  Thanks.  It seems to have uncovered some bugs in the later functionality (and how coins look/how the economy works).  Those don't seem to be related to any of these fixes, though.

**Pull request merged**
