### PR TITLE
Equip bugfix

### PR DESCRIPTION
**Pull request by feend78**
Fixed an issue where the 'equip', 'wear', and 'wield' commands could target items in a the room but not in the caller's inventory that came up while investigating issue #69

### CODE REVIEW

**Comment by feend78** [comment]
One point of discussion: in this PR, I created a function that handles searching only the caller's contents for an item as a private module level function, but I could also see it being useful in other contexts, so perhaps its name should not begin with an underscore. Comments appreciated

**Comment by ergodicbreak** [comment]
It does seem like a useful utility function. Given the `candidates` argument I'm wondering if there's some way to incorporate this without expanding the existing API, but I don't see how you'd do that with a custom error message. 

(also sorry for the long delay on replying to this!)

**Comment by feend78** [comment]
I agree that it's unfortunate to create an additional `search_inventory` method, but when the character's inventory is empty, calling the default `search` with candidates=self.contents evaluates `self.contents` as False (empty list), and `search` then falls back to the default candidates list, which includes the room contents.

In my last commit, I moved the `search_inventory` function onto the Character typeclass, which I think makes more sense than as a module function in a command-based module.

**Comment by stefanludlow** [comment]
Agreed.

**Comment by Griatch** [comment]
@feend78 

I don't agree. I think it sounds like a bug in the Evennia search mechanism if passing it an empty list for candidates doesn't return the empty list (since there are no candidates to search). It should only default if `candidates = None` rather than `candidates = []`. I made an issue against Evennia [here](https://github.com/evennia/evennia/issues/1016).

**Comment by feend78** [comment]
Thanks @Griatch. I'll keep an eye on that issue and rework this branch to just use `search`.

**Pull request merged**
