### PR TITLE
Overhaul the combat system

### PR DESCRIPTION
**Pull request by InspectorCaracal**
Completely rewriting the combat system, including much of the weapons system.

- Combat handlers are no longer a script, reducing DB calls.
- Combat will be real-time with cooldowns instead of turn-based with a queue.
- Weapons will be redesigned to use prototype-friendly attributes and tags instead of hard-coded typeclasses, making content expansion easier and allowing for things such as bludgeoning someone with your crossbow.

### CODE REVIEW

**Review by ChrisLR — COMMENTED** [review]
Very good start!
Consider breaking the next parts into smaller PRs.
+1 for using AttributeProperties and Tags

Not approving since it is still draft... but even then I don't have the rights to merge PRs :D

**Comment by InspectorCaracal** [comment]
> Very good start! Consider breaking the next parts into smaller PRs. +1 for using AttributeProperties and Tags
> 
> Not approving since it is still draft... but even then I don't have the rights to merge PRs :D

Yeah, I probably should have done the weapon tweaks separately, but there's enough stuff there I have to hook into that I figured I could at least do enough to make my main task easier. >.>

**Comment by InspectorCaracal** [comment]
Okay, I believe this is sufficiently done for one PR.

Other things that still need to be done before combat is playable, but can be done as separate PRs:
- Damage/defense logic on characters
- Combat prompt
- Unit tests
- Special attacks
- Integration of skill checks into weapon attacks
- Dual-wielding
- Revised weapon prototypes
- NPC combat AI

**Review by ChrisLR — APPROVED** [review]
Good start!
Opened up issue #126 for the remaining elements you noted.

**Pull request merged**
