### PR TITLE
basic python2 to 3 adjustments

### PR DESCRIPTION
**Pull request by friarzen**
Updates to Master to at least get the game up and running and able to log in and create a character.
Equipment purchases still trigger an evmenu failure.

### CODE REVIEW

**Comment by Griatch** [comment]
Good to see an initiative to get this done!

**Comment by friarzen** [comment]
How do I set the Travis-CI for this branch to python 3.7?

**Comment by Griatch** [comment]
@friarzen You need to modify the `.travis.yml` file in the root of the `ainneve` repository. Take a look at the equivalent in the `evennia` repo, it's already set up for Python 3.7.

**Comment by Griatch** [comment]
@friarzen It looks like @chainsol is MIA. I'd suggest merging this in order to proceed. Double-check also why the travis build fails at that time.

**Review by Griatch — APPROVED** [review]

**Pull request merged**
