### PR TITLE
added empty logfiles to cheat the following error

### PR DESCRIPTION
**Pull request by VoidFox**
IOError: [Errno 2] No such file or directory: '---------------gits/ainneve/server/logs/http_requests.log

### CODE REVIEW

**Comment by ergodicbreak** [comment]
This is OK to merge but I think it really belongs upstream in Evennia no?

**Comment by ergodicbreak** [comment]
Also, maybe I'm reading the history wrong, but I think we merged more from VoidFox than we wanted here? The archetypes branch got merged. @whitenoiseoss you may want to revert this. 

edit: OK, looking at #5 I see your note. But I don't think VoidFox meant to merge that branch and then include it in his PR.

**Comment by Griatch** [comment]
This is already closed; but it should be noted that these empty log files _are_ created by evennia. Log files are however excluded by the .gitignore file on the game dir- this usually makes sense but we might want to make sure evennia creates these files rather than erroring out when they are not found. 
I would suggest making an issue against evennia to this effect.

**Comment by VoidFox** [comment]
Sorry for the confusion! 
Didnt know my pull request would include the merging i did after it.

Didnt want to make an issue on Evennia for this, becouse its the first time ive seen this happening.
And yes, this non-issue was created by .gitignore

"evennia --init gamename"  creates server/logs/server.log
"evennia migrate"                creates the others,  -> but only if server.log exists! <-

So in the End this Problem should never show on a clean Installation.

**Comment by Griatch** [comment]
As of evennia/evennia@72049eeddd09ecee9a7b9dcfb401d2f38702c75a Evennia will now give a graceful warning and tell the user to manually create the missing log folder rather than throw a traceback.

**Pull request merged**
